const TIMETABLE_SUCCESS = 'TIMETABLE_SUCCESS';
const TIMETABLE_ERROR = 'TIMETABLE_ERROR';
const TIMETABLE_INIT = 'TIMETABLE_INIT';

module.exports = {
    TIMETABLE_SUCCESS,
    TIMETABLE_ERROR,
    TIMETABLE_INIT
}